language: node_js
node_js:
- '5.7'
cache:
  directories:
  - node_modules
notifications:
  slack:
    secure: mF8vqzwZL3BU2ne5PZHe2kCrWa5g3MkKSoFrkM5ZprnAfAx2zViIZQm2FDr3LpaZb9xefmbPwWxksTPvY2COxCxeU4k/FYHqRPR4h7b7PTtv67dbZN/kfkE9MuwuG/MKmbYcEcBlUegnJQAasEn3O4TmrziLLNfnvLt/zjzvitmBPubDrMzE/3KxRfDB/RoinmRVPPoDLk5c6jEUcMEpchlaG544wGXtT7U5ojSHPzg3QJSQKh2B41CUO+mlXNM466Ql9AgSpcqScl6i+2BeBjv2D5LyRKyfBn4nBFt7f62NKI95u752nn4CFDnYzLDJrOwUCAw8lgKnLYhMbyA779mKUKvJVoBFYZwhZ5+YxavvOP+rmwoogFxOlAwgqFeJdvcJ69RG1i3yETJxEsjuT1Vs8amX25f3twC7wAtOSKtG/r+u1StdasqkYy8eoA+YUsAx82CmiSPJ2Th0mFonMzH0bIWhw6JBjlICfKbCeevJErr/Wd5RKoone2mXo1rLTznlcgilI/X3kPzGDdYGaWyLb+kbFOmGDippDYv5ch8P3xOotS2yjxpTIzo0biucdfLIfL4VxWJLKqiD1c2p0jBOyMZVEuNqUta5Jpub8TLbWhX9tHyvd38tfagmR4oUCrKMIuiCFX6x1kKTsefw/8ZdylMJkE2WBJbjnx2otBA=
